#OLD  PPO/ppo_training_phases_config.py

TRAINING_PHASES = {

    "Refresh_Random": {
        "duration": 100,
        "opponent_mix": {
            "R":  0.90,
            "POP": 0.05,
            "SP": 0.05,
        },
        "params": {
            "lr":              1050e-7,
            "clip":            0.20,
            "entropy":         0.0044,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.19,
            "max_grad_norm":   0.5,
            "target_kl":       0.0175,
            "temperature":     1.12,

            "center_start":    1.00,
            "guard_prob":     1.00,
            "win_now_prob":    1.00,
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.06,
            "mentor_depth": 7,
            "mentor_prob": 0.35,
            "mentor_coef": 0.18,
        },
    },
    
    "Refresh_L1": {
        "duration": 100,
        "opponent_mix": {
            "L1":  0.90,
            "POP": 0.05,
            "SP": 0.05,
        },
        "params": {
            "lr":              1050e-7,
            "clip":            0.20,
            "entropy":         0.0044,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.19,
            "max_grad_norm":   0.5,
            "target_kl":       0.0175,
            "temperature":     1.12,

            "center_start":    1.00,
            "guard_prob":     1.00,
            "win_now_prob":    1.00,
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.06,
            "mentor_depth": 7,
            "mentor_prob": 0.35,
            "mentor_coef": 0.18,
        },
    },
    
    "Refresh_L2": {
        "duration": 100,
        "opponent_mix": {
            "L2":  0.90,
            "POP": 0.05,
            "SP": 0.05,
        },
        "params": {
            "lr":              1050e-7,
            "clip":            0.20,
            "entropy":         0.0044,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.19,
            "max_grad_norm":   0.5,
            "target_kl":       0.0175,
            "temperature":     1.12,

            "center_start":    1.00,
            "guard_prob":     1.00,
            "win_now_prob":    1.00,
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.06,
            "mentor_depth": 7,
            "mentor_prob": 0.35,
            "mentor_coef": 0.18,
        },
    },
    
    "Refresh_L3": {
        "duration": 100,
        "opponent_mix": {
            "L3":  0.90,
            "POP": 0.05,
            "SP": 0.05,
        },
        "params": {
            "lr":              1050e-7,
            "clip":            0.20,
            "entropy":         0.0044,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.19,
            "max_grad_norm":   0.5,
            "target_kl":       0.0175,
            "temperature":     1.12,

            "center_start":    1.00,
            "guard_prob":     1.00,
            "win_now_prob":    1.00,
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.06,
            "mentor_depth": 7,
            "mentor_prob": 0.35,
            "mentor_coef": 0.18,
        },
    },

    "Mixed_L3_focus": {
        "duration": 700,
        "opponent_mix": {
            "L1":  0.21,
            "L2": 0.22,
            "L3": 0.45,
            "L4": 0.01,
            "L5": 0.01,
            "POP": 0.05,
            "SP": 0.05,
        },
        "params": {
            "lr":              1050e-7,
            "clip":            0.20,
            "entropy":         0.0044,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.19,
            "max_grad_norm":   0.5,
            "target_kl":       0.0175,
            "temperature":     1.12,

            "center_start":    0.85,
            "guard_prob":      0.56,
            "win_now_prob":    0.89,
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.05,
            "mentor_depth": 7,
            "mentor_prob": 0.30,
            "mentor_coef": 0.18,
        },
    },

    "L3_power": {
        "duration": 700,
        "opponent_mix": {
            "L1":  0.23,
            "L2": 0.15,
            "L3": 0.50,
            "L4": 0.01,
            "L5": 0.01,
            "POP": 0.05,
            "SP": 0.05,
        },
        "params": {
            "lr":              1000e-7,
            "clip":            0.20,
            "entropy":         0.0040,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.19,
            "max_grad_norm":   0.5,
            "target_kl":       0.0170,
            "temperature":     1.11,

            "center_start":    0.84,
            "guard_prob":      0.55,
            "win_now_prob":    0.88,
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.03,
            "mentor_depth": 7,
            "mentor_prob": 0.20,
            "mentor_coef": 0.12,
        },
    },

    "L3_Force": {
        "duration": 700,
        "opponent_mix": {
            "L1":  0.15,
            "L2": 0.10,
            "L3": 0.60,
            "L4": 0.02,
            "L5": 0.03,
            "POP": 0.05,
            "SP": 0.05,
        },
        "params": {
            "lr":              999e-7,
            "clip":            0.20,
            "entropy":         0.0039,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.185,
            "max_grad_norm":   0.5,
            "target_kl":       0.0170,
            "temperature":     1.10,

            "center_start":    0.83,
            "guard_prob":      0.54,
            "win_now_prob":    0.87,
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.02,
            "mentor_depth": 7,
            "mentor_prob": 0.15,
            "mentor_coef": 0.08,
        },
    },

    "L3_Major": {
        "duration": 700,
        "opponent_mix": {
            "L1":  0.10,
            "L2": 0.05,
            "L3": 0.77,
            "L4": 0.02,
            "L5": 0.03,
            "POP": 0.02,
            "SP": 0.01,
        },
        "params": {
            "lr":              997e-7,
            "clip":            0.20,
            "entropy":         0.0039,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.184,
            "max_grad_norm":   0.5,
            "target_kl":       0.0169,
            "temperature":     1.10,

            "center_start":    0.82,
            "guard_prob":      0.53,
            "win_now_prob":    0.86,
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.01,
            "mentor_depth": 7,
            "mentor_prob": 0.10,
            "mentor_coef": 0.05,
        },
    },

    "L3_Finale": {
        "duration": 700,
        "opponent_mix": {
            "L1":  0.05,
            "L3": 0.83,
            "L4": 0.02,
            "L5": 0.08,
            "L6": 0.01,
            "L7": 0.01,
            "POP": 0.00,
            "SP": 0.00,
        },
        "params": {
            "lr":              996e-7,
            "clip":            0.20,
            "entropy":         0.0038,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.183,
            "max_grad_norm":   0.5,
            "target_kl":       0.0168,
            "temperature":     1.09,

            "center_start":    0.81,
            "guard_prob":      0.52,
            "win_now_prob":    0.85,
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.00,
            "mentor_depth": 7,
            "mentor_prob": 0.05,
            "mentor_coef": 0.03,
        },
    },



}
# PPO/ppo_training_phases_config.py

TRAINING_PHASES = {

    "Refresh_Random": {
        "duration": 100,
        "opponent_mix": {
            "R":  0.90,
            "POP": 0.05,
            "SP": 0.05,
        },
        "params": {
            "lr":              1050e-7,
            "clip":            0.20,
            "entropy":         0.0044,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.19,
            "max_grad_norm":   0.5,
            "target_kl":       0.0175,
            "temperature":     1.06,
            "center_start": 0.95,   
            "guard_prob":   0.95,   
            "win_now_prob": 0.95,   
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.05,
            "mentor_depth": 7,
            "mentor_prob": 0.25,
            "mentor_coef": 0.13,
        },
    },

    "Refresh_L1": {
        "duration": 100,
        "opponent_mix": {
            "L1":  0.90,
            "POP": 0.05,
            "SP": 0.05,
        },
        "params": {
            "lr":              1050e-7,
            "clip":            0.20,
            "entropy":         0.0044,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.19,
            "max_grad_norm":   0.5,
            "target_kl":       0.0175,
            "temperature":     1.06,
            "center_start": 0.95,   
            "guard_prob":   0.95,   
            "win_now_prob": 0.95,   
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.05,
            "mentor_depth": 7,
            "mentor_prob": 0.25,
            "mentor_coef": 0.13,
        },
    },

    "Bridge_L1_L2": {
        "duration": 500,
        "opponent_mix": {
            "R":   0.15,
            "L1":  0.35,
            "L2":  0.35,
            "L3":  0.05,
            "POP": 0.05,
            "SP":  0.05,
        },
        "params": {
            "lr":              9.9e-5,   # small step down from L3_Finale
            "clip":            0.20,
            "entropy":         0.0040,   # slightly higher to encourage exploration vs shallow
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.183,
            "max_grad_norm":   0.5,
            "target_kl":       0.0168,
            "temperature":     1.09,

            "center_start":    0.85,
            "guard_prob":      0.52,
            "win_now_prob":    0.86,
            "guard_ply_min":   5,
            "guard_ply_max":   13,

            # mentors: soft guidance
            "distill_coef":    0.015,
            "mentor_depth":    7,
            "mentor_prob":     0.12,
            "mentor_coef":     0.05,
        },
    },

    "L2_Main": {
        "duration": 700,
        "opponent_mix": {
            "R":   0.05,
            "L1":  0.20,
            "L2":  0.45,
            "L3":  0.20,
            "POP": 0.05,
            "SP":  0.05,
        },
        "params": {
            "lr":              9.8e-5,
            "clip":            0.20,
            "entropy":         0.0039,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.183,
            "max_grad_norm":   0.5,
            "target_kl":       0.0167,
            "temperature":     1.09,

            "center_start":    0.82,
            "guard_prob":      0.50,
            "win_now_prob":    0.85,

            "guard_ply_min":   5,
            "guard_ply_max":   13,

            "distill_coef":    0.010,
            "mentor_depth":    7,
            "mentor_prob":     0.10,
            "mentor_coef":     0.04,
        },
    },

    "Refresh_L2": {
        "duration": 100,
        "opponent_mix": {
            "L2":  0.90,
            "POP": 0.05,
            "SP": 0.05,
        },
        "params": {
            "lr":              1025e-7,
            "clip":            0.20,
            "entropy":         0.0044,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.19,
            "max_grad_norm":   0.5,
            "target_kl":       0.0175,
            "temperature":     1.06,
            "center_start": 0.95,   
            "guard_prob":   0.95,   
            "win_now_prob": 0.95,   
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.05,
            "mentor_depth": 7,
            "mentor_prob": 0.25,
            "mentor_coef": 0.13,
        },
    },

    "Balanced_L2_L3": {
        "duration": 700,
        "opponent_mix": {
            "R":   0.03,
            "L1":  0.10,
            "L2":  0.32,
            "L3":  0.40,
            "L4":  0.05,
            "L5":  0.05,
            "POP": 0.03,
            "SP":  0.02,
        },
        "params": {
            "lr":              9.6e-5,
            "clip":            0.20,
            "entropy":         0.0038,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.182,
            "max_grad_norm":   0.5,
            "target_kl":       0.0166,
            "temperature":     1.08,

            "center_start":    0.80,
            "guard_prob":      0.48,
            "win_now_prob":    0.84,

            "guard_ply_min":   5,
            "guard_ply_max":   13,

            "distill_coef":    0.005,    # mentors barely whisper now
            "mentor_depth":    7,
            "mentor_prob":     0.08,
            "mentor_coef":     0.03,
        },
    },

    "Refresh_L3": {
        "duration": 100,
        "opponent_mix": {
            "L3":  0.90,
            "POP": 0.05,
            "SP": 0.05,
        },
        "params": {
            "lr":              1050e-7,
            "clip":            0.20,
            "entropy":         0.0044,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.19,
            "max_grad_norm":   0.5,
            "target_kl":       0.0175,
            "temperature":     1.06,
            "center_start": 0.95,   
            "guard_prob":   0.95,   
            "win_now_prob": 0.95,   
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.05,
            "mentor_depth": 7,
            "mentor_prob": 0.25,
            "mentor_coef": 0.13,
        },
    },

    "SelfPlay_L2L3": {
        "duration": 200,
        "opponent_mix": {
            "R":   0.05,
            "L1":  0.10,
            "L2":  0.25,
            "L3":  0.25,
            "POP": 0.10,
            "SP":  0.25,      # lots of self-play here
        },
        "params": {
            "lr":              9.5e-5,
            "clip":            0.20,
            "entropy":         0.0037,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.182,
            "max_grad_norm":   0.5,
            "target_kl":       0.0165,
            "temperature":     1.08,

            "center_start":    0.78,
            "guard_prob":      0.47,
            "win_now_prob":    0.84,

            "guard_ply_min":   5,
            "guard_ply_max":   13,

            "distill_coef":    0.0,     # no more explicit distillation in the finale
            "mentor_depth":    7,
            "mentor_prob":     0.05,
            "mentor_coef":     0.02,
        },
    },

    "Mixed_L3_focus": {
        "duration": 700,
        "opponent_mix": {
            "L1":  0.21,
            "L2": 0.22,
            "L3": 0.45,
            "L4": 0.01,
            "L5": 0.01,
            "POP": 0.05,
            "SP": 0.05,
        },
        "params": {
            "lr":              975e-7,
            "clip":            0.20,
            "entropy":         0.0044,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.19,
            "max_grad_norm":   0.5,
            "target_kl":       0.0175,
            "temperature":     1.10,

            "center_start":    0.85,
            "guard_prob":      0.56,
            "win_now_prob":    0.89,
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.05,
            "mentor_depth": 7,
            "mentor_prob": 0.30,
            "mentor_coef": 0.18,
        },
    },

    "L3_power": {
        "duration": 700,
        "opponent_mix": {
            "L1":  0.23,
            "L2": 0.15,
            "L3": 0.50,
            "L4": 0.01,
            "L5": 0.01,
            "POP": 0.05,
            "SP": 0.05,
        },
        "params": {
            "lr":              950e-7,
            "clip":            0.20,
            "entropy":         0.0040,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.19,
            "max_grad_norm":   0.5,
            "target_kl":       0.0170,
            "temperature":     1.09,

            "center_start":    0.84,
            "guard_prob":      0.55,
            "win_now_prob":    0.88,
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.03,
            "mentor_depth": 7,
            "mentor_prob": 0.20,
            "mentor_coef": 0.12,
        },
    },

    "L3_Force": {
        "duration": 700,
        "opponent_mix": {
            "L1":  0.15,
            "L2": 0.10,
            "L3": 0.60,
            "L4": 0.02,
            "L5": 0.03,
            "POP": 0.05,
            "SP": 0.05,
        },
        "params": {
            "lr":              925e-7,
            "clip":            0.20,
            "entropy":         0.0039,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.185,
            "max_grad_norm":   0.5,
            "target_kl":       0.0170,
            "temperature":     1.08,

            "center_start":    0.83,
            "guard_prob":      0.54,
            "win_now_prob":    0.87,
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.02,
            "mentor_depth": 7,
            "mentor_prob": 0.15,
            "mentor_coef": 0.08,
        },
    },

    "L3_Major": {
        "duration": 700,
        "opponent_mix": {
            "L1":  0.10,
            "L2": 0.05,
            "L3": 0.77,
            "L4": 0.02,
            "L5": 0.03,
            "POP": 0.02,
            "SP": 0.01,
        },
        "params": {
            "lr":              920e-7,
            "clip":            0.20,
            "entropy":         0.0039,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.184,
            "max_grad_norm":   0.5,
            "target_kl":       0.0169,
            "temperature":     1.06,

            "center_start":    0.82,
            "guard_prob":      0.53,
            "win_now_prob":    0.86,
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.01,
            "mentor_depth": 7,
            "mentor_prob": 0.10,
            "mentor_coef": 0.05,
        },
    },

    "L3_Finale": {
        "duration": 700,
        "opponent_mix": {
            "L1":  0.05,
            "L3": 0.83,
            "L4": 0.02,
            "L5": 0.08,
            "L6": 0.01,
            "L7": 0.01,
            "POP": 0.00,
            "SP": 0.00,
        },
        "params": {
            "lr":              910e-7,
            "clip":            0.20,
            "entropy":         0.0038,
            "epochs":          4,
            "batch_size":      256,
            "steps_per_update": 128,
            "vf_clip":         0.183,
            "max_grad_norm":   0.5,
            "target_kl":       0.0168,
            "temperature":     1.05,

            "center_start":    0.81,
            "guard_prob":      0.52,
            "win_now_prob":    0.85,
            "guard_ply_min":   5,
            "guard_ply_max":   13,
            "distill_coef":    0.00,
            "mentor_depth": 7,
            "mentor_prob": 0.05,
            "mentor_coef": 0.03,
        },
    },



}
