#!/usr/bin/env python3
"""
Convert curated John Tromp / James D. Allen Connect-Four joseki and match lines
into the same move-row format used by the Connect4 project.

Source page:
    https://tromp.github.io/c4.html

What this script writes
-----------------------
Rows in the same broad schema as c4_move_data_generator.py:

    label, reward, game, ply, action, p0..p6, player, 0-0..5-6

Board convention:
    - numpy shape (6, 7)
    - board[0, :] is the top row
    - board[5, :] is the bottom row
    - values are {0, 1, 2}
        0 = empty
        1 = first player / X / Eques / uppercase source moves
        2 = second player / O / Knott / lowercase source moves

Two output families are supported:

1) Expert rows, from the curated Tromp/Allen move sequences.
   For every unique prefix, the next expert move(s) become p0..p6.
   If multiple curated lines share a position with different expert continuations,
   the policy is uniform over those shown continuations.

2) Optional LA rows, generated from the same joseki prefixes.
   For every unique prefix position, your Connect4Lookahead labels the position
   with action and p0..p6 uniform among tied-best moves.

Spyder usage
------------
Place this file somewhere inside your project tree. If it lives inside C4/, the
script automatically adds the parent project directory to sys.path and imports:

    from C4.fast_connect4_lookahead import Connect4Lookahead

Then just press Run.

Important
---------
The curated move list below is intentionally small and readable. It contains
clear linear move lines from the Tromp page. Add more lines to CURATED_LINES
using the same syntax if you want to expand the pack.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple
import re
import random
import sys

import numpy as np
import pandas as pd


# =============================================================================
# One-click configuration
# =============================================================================

OUTPUT_PATH = Path("Tromp_Joseki_rows.xlsx")
SHEET_NAME = "Sheet1"

# Write expert policy rows extracted from Tromp/Allen move sequences.
INCLUDE_EXPERT_ROWS = True

# Also write rows where the positions are taken from Tromp/Allen prefixes, but
# the label/action/policy is generated by your current lookahead agent.
INCLUDE_LA_PREFIX_ROWS = True
LOOKAHEAD_DEPTHS = [7, 9, 11, 13]

# Prefix range for LA rows. None means no upper bound.
LA_MIN_PREFIX_PLIES = 0
LA_MAX_PREFIX_PLIES: Optional[int] = None

# If True, p0..p6 are written. Recommended for your supervised pipeline.
STORE_POLICY_PROBS = True

# How to choose a single action from tied p0..p6.
# "center" = center-first order, "left" = smallest column, "sample" = seeded sample.
ACTION_MODE = "center"
SEED = 666

# Optional visual sanity printout.
PRINT_FIRST_N_BOARDS = 8


# =============================================================================
# Curated source lines
# =============================================================================

# The syntax is simple: any tokens matching A1..G6 or a1..g6 are extracted.
# Uppercase = player 1 / X / Eques.
# Lowercase = player 2 / O / Knott.
# The digit is used as a gravity validation check. The actual action is the column.
#
# These are intentionally clear linear lines from the Tromp/Allen page: opening
# game tree examples, joseki examples, and the six real match games. Some match
# games contain human errors; they are labeled as match lines, not joseki.
CURATED_LINES: List[Tuple[str, str, str]] = [
    # -------------------------------------------------------------------------
    # Opening Game Tree / Joseki chart excerpts
    # -------------------------------------------------------------------------
    (
        "Joseki_01",
        "joseki",
        "D1 d2 D3 d4 D5 e1 E2 e3 E4 b1 B2 b3 B4 b5 G1 d6 F1 g2 C1 f2 F3 f4 F5",
    ),
    (
        "Joseki_13_long",
        "joseki",
        "D1 d2 D3 c1 C2 c3 C4 g1 G2 g3 E1 e2 C5 a1 G4 c6 G5 g6 E3 e4 E5 a2 A3 a4 A5 a6 E6 b1 B2",
    ),
    (
        "Joseki_20",
        "joseki",
        "D1 e1 A1 d2 D3 d4 B1 c1 C2 c3 E2 c4 D5 c5 C6 f1 D6",
    ),
    (
        "Joseki_16",
        "joseki",
        "D1 e1 A1 c1 C2 c3 C4 e2 E3 d2 E4 e5 F1 d3 D4 d5 F2",
    ),
    (
        "Joseki_17_diag_4_2",
        "joseki",
        "D1 e1 A1 c1 C2 c3 C4 e2 E3 e4 D2 d3 E5 c5 A2",
    ),
    (
        "Joseki_18",
        "joseki",
        "D1 e1 A1 e2 B1 c1 B2 b3 C2 c3 D2 a2 D3 d4",
    ),
    (
        "Joseki_23_short",
        "joseki",
        "D1 e1 B1 b2 A1 c1 C2 c3 C4 e2 C5",
    ),
    (
        "Joseki_25_long",
        "joseki",
        "D1 e1 B1 b2 A1 c1 C2 c3 E2 c4 G1 c5 C6 a2 E3 e4 E5 e6 G2 b3 B4",
    ),

    # -------------------------------------------------------------------------
    # Text examples / variations from the article
    # -------------------------------------------------------------------------
    (
        "Game3_Variation_F1",
        "variation",
        "D1 d2 D3 c1 C2 c3 C4 f1 F2 f3 D4 c5 G1 f4",
    ),
    (
        "Game3_Variation_D4",
        "variation",
        "D1 d2 D3 c1 C2 c3 C4 d4 F1 g1 F2 f3 D5 c5 F4",
    ),
    (
        "Problem_A_solution",
        "problem_solution",
        "G1 e1 G2 g3 E2 g4",
    ),
    (
        "Problem_F_solution",
        "problem_solution",
        "A3 e2 E3 e4 A4 a5 E5 b5 D2 d3 D4",
    ),

    # -------------------------------------------------------------------------
    # The six real match games shown on the page.
    # These are useful as a tiny human/expert trajectory pack, but they may
    # include deliberately nonstandard openings and mistakes.
    # -------------------------------------------------------------------------
    (
        "Match_Game_1",
        "match",
        "D1 c1 G1 d2 D3 d4 F1 e1 E2 e3 C2 e4 D5 e5 E6 b1 D6",
    ),
    (
        "Match_Game_2",
        "match",
        "D1 e1 B1 e2 B2 b3 D2 e3 E4 a1 D3 d4 B4 a2 D5 a3 A4 a5 E5",
    ),
    (
        "Match_Game_3",
        "match",
        "B1 b2 E1 d1 D2 d3 D4 d5 D6 e2 E3 f1",
    ),
    (
        "Match_Game_4",
        "match",
        "C1 b1 B2 b3 D1 d2 B4 e1 E2 d3 D4 c2 C3 a1 D5 d6 B5 g1 B6",
    ),
    (
        "Match_Game_5",
        "match",
        "B1 b2 E1 d1 E2 e3 D2 e4 E5 a1 G1 d3 D4 b3 B4 g2",
    ),
    (
        "Match_Game_6",
        "match",
        "C1 b1 B2 f1 B3 b4 F2 f3 F4 e1 F5",
    ),
]


# =============================================================================
# Constants and low-level helpers
# =============================================================================

ROWS = 6
COLS = 7
CENTER_COL = 3
CENTER_ORDER = (3, 4, 2, 5, 1, 6, 0)
TOKEN_RE = re.compile(r"\b([A-Ga-g][1-6])\b")

COL_TO_INDEX = {ch: i for i, ch in enumerate("ABCDEFG")}


@dataclass(frozen=True)
class MoveToken:
    raw: str
    col: int
    source_row_bottom_based: int  # 1..6 from source notation
    player: int                   # 1 for uppercase/X, 2 for lowercase/O


def _parse_move_tokens(text: str) -> List[MoveToken]:
    out: List[MoveToken] = []
    for m in TOKEN_RE.finditer(text):
        raw = m.group(1)
        col = COL_TO_INDEX[raw[0].upper()]
        row_num = int(raw[1])
        player = 1 if raw[0].isupper() else 2
        out.append(MoveToken(raw=raw, col=col, source_row_bottom_based=row_num, player=player))
    return out


def _empty_board() -> np.ndarray:
    return np.zeros((ROWS, COLS), dtype=np.int8)


def _board_key(board: np.ndarray) -> Tuple[int, ...]:
    return tuple(int(x) for x in board.reshape(-1))


def _legal_cols(board: np.ndarray) -> List[int]:
    return [c for c in range(COLS) if int(board[0, c]) == 0]


def _lowest_empty_row(board: np.ndarray, col: int) -> int:
    for r in range(ROWS - 1, -1, -1):
        if int(board[r, col]) == 0:
            return r
    return -1


def _has_four_from(board: np.ndarray, row: int, col: int, token: int) -> bool:
    for dr, dc in ((0, 1), (1, 0), (1, 1), (1, -1)):
        cnt = 1

        rr, cc = row + dr, col + dc
        while 0 <= rr < ROWS and 0 <= cc < COLS and int(board[rr, cc]) == token:
            cnt += 1
            rr += dr
            cc += dc

        rr, cc = row - dr, col - dc
        while 0 <= rr < ROWS and 0 <= cc < COLS and int(board[rr, cc]) == token:
            cnt += 1
            rr -= dr
            cc -= dc

        if cnt >= 4:
            return True
    return False


def _apply_source_move(board: np.ndarray, mv: MoveToken, *, strict_rows: bool = True) -> Tuple[np.ndarray, int]:
    row = _lowest_empty_row(board, mv.col)
    if row < 0:
        raise ValueError(f"Illegal full-column move {mv.raw}")

    expected_source_row = ROWS - row  # project row 5 -> source row 1
    if strict_rows and expected_source_row != mv.source_row_bottom_based:
        raise ValueError(
            f"Gravity/row mismatch for {mv.raw}: source says row {mv.source_row_bottom_based}, "
            f"but token would land on row {expected_source_row}"
        )

    nxt = np.array(board, copy=True)
    nxt[row, mv.col] = int(mv.player)
    return nxt, row


def _board_to_cells(board: np.ndarray) -> Dict[str, int]:
    out: Dict[str, int] = {}
    for r in range(ROWS):
        for c in range(COLS):
            out[f"{r}-{c}"] = int(board[r, c])
    return out


def _infer_player_to_move(board: np.ndarray) -> int:
    x = int(np.count_nonzero(board == 1))
    o = int(np.count_nonzero(board == 2))
    if x == o:
        return 1
    if x == o + 1:
        return 2
    raise ValueError(f"Illegal counts: X={x}, O={o}")


def _ply_to_move(board: np.ndarray) -> int:
    return int(np.count_nonzero(board) + 1)


def _uniform_probs_over(cols: Iterable[int]) -> np.ndarray:
    cols = sorted(set(int(c) for c in cols))
    probs = np.zeros(COLS, dtype=np.float64)
    if not cols:
        return probs
    p = 1.0 / float(len(cols))
    for c in cols:
        probs[c] = p
    return probs


def _uniform_among_best(scores: np.ndarray, legal_cols: Iterable[int]) -> np.ndarray:
    legal = list(int(c) for c in legal_cols)
    probs = np.zeros(COLS, dtype=np.float64)
    if not legal:
        return probs
    best = np.nanmax([float(scores[c]) for c in legal])
    best_cols = [c for c in legal if np.isfinite(scores[c]) and np.isclose(scores[c], best, atol=1e-9, rtol=1e-9)]
    if not best_cols:
        return probs
    p = 1.0 / float(len(best_cols))
    for c in best_cols:
        probs[c] = p
    return probs


def _choose_action_from_probs(probs: np.ndarray, mode: str, rng: random.Random) -> int:
    cols = [c for c in range(COLS) if float(probs[c]) > 0.0]
    if not cols:
        return CENTER_COL

    mode = str(mode).lower()
    if mode == "sample":
        total = float(probs.sum())
        x = rng.random() * total
        acc = 0.0
        for c in range(COLS):
            acc += float(probs[c])
            if x <= acc:
                return int(c)
        return int(cols[-1])

    if mode == "left":
        return int(min(cols))

    for c in CENTER_ORDER:
        if c in cols:
            return int(c)
    return int(cols[0])


def _records_to_dataframe(records: List[Dict[str, Any]]) -> pd.DataFrame:
    if not records:
        return pd.DataFrame()
    df = pd.DataFrame.from_records(records)
    board_cols = [f"{r}-{c}" for r in range(ROWS) for c in range(COLS)]
    head_cols = [c for c in ["label", "reward", "game", "ply"] if c in df.columns]
    extra_cols = [c for c in df.columns if c not in set(head_cols + board_cols)]
    return df[head_cols + sorted(extra_cols) + [c for c in board_cols if c in df.columns]]


def _write_output(df: pd.DataFrame, output_path: Path, sheet_name: str = "Sheet1") -> None:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    suffix = output_path.suffix.lower()

    if suffix == ".xlsx":
        with pd.ExcelWriter(output_path, engine="openpyxl", mode="w") as w:
            df.to_excel(w, sheet_name=sheet_name, index=False)
        return

    if suffix == ".csv":
        df.to_csv(output_path, index=False)
        return

    if suffix == ".parquet":
        df.to_parquet(output_path, index=False)
        return

    raise ValueError(f"Unsupported output extension: {output_path.suffix}")


def _print_board(board: np.ndarray) -> None:
    sym = {0: ".", 1: "X", 2: "O"}
    for r in range(ROWS):
        print(" ".join(sym[int(board[r, c])] for c in range(COLS)))


# =============================================================================
# Sequence replay and row generation
# =============================================================================

def _validated_sequences(strict_rows: bool = True) -> List[Dict[str, Any]]:
    """
    Parse and validate CURATED_LINES.

    Returns a list of dictionaries with:
        source_id, source_kind, tokens

    Lines with invalid gravity are skipped and printed. Usually this means the
    source line is a contextual continuation rather than a line from the empty
    board; add its prefix if you want to use it.
    """
    valid: List[Dict[str, Any]] = []

    for source_id, source_kind, text in CURATED_LINES:
        tokens = _parse_move_tokens(text)
        board = _empty_board()
        ok = True

        for i, mv in enumerate(tokens):
            expected_player = 1 if (i % 2 == 0) else 2
            if mv.player != expected_player:
                print(
                    f"Skipping {source_id}: player mismatch at move {i + 1}: "
                    f"token {mv.raw} encodes player {mv.player}, expected {expected_player}"
                )
                ok = False
                break

            try:
                board, row = _apply_source_move(board, mv, strict_rows=strict_rows)
            except Exception as e:
                print(f"Skipping {source_id}: {e}")
                ok = False
                break

            # We allow terminal endings, but after a terminal move we stop adding
            # later moves from that source line, because they would not represent
            # a legal game continuation.
            if _has_four_from(board, row, mv.col, mv.player) and i < len(tokens) - 1:
                print(f"Truncating {source_id}: terminal after move {i + 1} ({mv.raw})")
                tokens = tokens[: i + 1]
                break

        if ok and tokens:
            valid.append(dict(source_id=source_id, source_kind=source_kind, tokens=tokens))

    return valid


def build_expert_rows(sequences: List[Dict[str, Any]], *, rng: random.Random) -> List[Dict[str, Any]]:
    """
    Build one row per unique board prefix.

    If multiple source lines show different expert continuations from the same
    prefix, p0..p6 is uniform over the union of shown next actions.
    """
    by_key: Dict[Tuple[int, ...], Dict[str, Any]] = {}

    for seq_id, seq in enumerate(sequences):
        source_id = str(seq["source_id"])
        source_kind = str(seq["source_kind"])
        tokens: List[MoveToken] = list(seq["tokens"])

        board = _empty_board()
        for move_index, mv in enumerate(tokens):
            key = _board_key(board)
            player = _infer_player_to_move(board)
            legal = _legal_cols(board)
            if mv.col not in legal:
                raise RuntimeError(f"Internal error: source move {mv.raw} is illegal in {source_id}")

            entry = by_key.get(key)
            if entry is None:
                entry = dict(
                    board=np.array(board, copy=True),
                    ply=_ply_to_move(board),
                    player=player,
                    actions=set(),
                    source_ids=set(),
                    source_kinds=set(),
                    source_moves=set(),
                    min_source_seq=int(seq_id),
                )
                by_key[key] = entry

            entry["actions"].add(int(mv.col))
            entry["source_ids"].add(source_id)
            entry["source_kinds"].add(source_kind)
            entry["source_moves"].add(mv.raw)

            board, row = _apply_source_move(board, mv, strict_rows=True)
            if _has_four_from(board, row, mv.col, mv.player):
                break

    rows: List[Dict[str, Any]] = []
    for game_id, entry in enumerate(by_key.values()):
        board = entry["board"]
        actions = sorted(int(a) for a in entry["actions"])
        probs = _uniform_probs_over(actions)
        action = _choose_action_from_probs(probs, ACTION_MODE, rng)

        row: Dict[str, Any] = {
            "label": "Tromp_Expert",
            "reward": 0.0,
            "game": int(game_id),
            "ply": int(entry["ply"]),
            "player": int(entry["player"]),
            "action": int(action),
            "source_count": int(len(entry["source_ids"])),
            "source_ids": "|".join(sorted(entry["source_ids"])),
            "source_kinds": "|".join(sorted(entry["source_kinds"])),
            "source_moves": "|".join(sorted(entry["source_moves"])),
            "expert_actions": ",".join(str(a) for a in actions),
            **_board_to_cells(board),
        }

        if STORE_POLICY_PROBS:
            for a in range(COLS):
                row[f"p{a}"] = float(probs[a])

        rows.append(row)

    return rows


def _import_lookahead():
    """Import Connect4Lookahead using the canonical C4 package path."""
    this_file = Path(__file__).resolve()

    # If this script sits in C4/, project root is parent.parent.
    # If this script sits in project root, project root is parent.
    if this_file.parent.name.lower() == "c4":
        project_root = this_file.parent.parent
    else:
        project_root = this_file.parent

    if str(project_root) not in sys.path:
        sys.path.insert(0, str(project_root))

    from C4.fast_connect4_lookahead import Connect4Lookahead

    return Connect4Lookahead


def build_la_prefix_rows(
    sequences: List[Dict[str, Any]],
    *,
    rng: random.Random,
    lookahead_depth: int,
) -> List[Dict[str, Any]]:
    """
    Build synthetic rows from Tromp/Allen prefix positions, labeled by LA.

    One call creates rows for one lookahead depth.
    Use main() to call this repeatedly for L7, L9, L11, L13.
    """
    Connect4Lookahead = _import_lookahead()
    la = Connect4Lookahead()

    depth = int(lookahead_depth)

    seen: set[Tuple[int, ...]] = set()
    rows: List[Dict[str, Any]] = []

    for seq in sequences:
        source_id = str(seq["source_id"])
        source_kind = str(seq["source_kind"])
        tokens: List[MoveToken] = list(seq["tokens"])

        board = _empty_board()

        for prefix_plies in range(0, len(tokens) + 1):
            if (
                prefix_plies >= LA_MIN_PREFIX_PLIES
                and (LA_MAX_PREFIX_PLIES is None or prefix_plies <= LA_MAX_PREFIX_PLIES)
            ):
                key = _board_key(board)

                if key not in seen and _legal_cols(board):
                    seen.add(key)

                    player = _infer_player_to_move(board)
                    legal = _legal_cols(board)

                    scores = la.n_step_action_scores(board, player, depth=depth)
                    probs = _uniform_among_best(scores, legal)
                    action = _choose_action_from_probs(probs, ACTION_MODE, rng)

                    row: Dict[str, Any] = {
                        "label": f"Tromp_LA{depth}_prefix",
                        "reward": 0.0,
                        "game": int(len(rows)),
                        "ply": int(_ply_to_move(board)),
                        "player": int(player),
                        "action": int(action),
                        "la_depth": int(depth),
                        "source_id": source_id,
                        "source_kind": source_kind,
                        "prefix_plies": int(prefix_plies),
                        **_board_to_cells(board),
                    }

                    if STORE_POLICY_PROBS:
                        for a in range(COLS):
                            row[f"p{a}"] = float(probs[a])

                    rows.append(row)

            if prefix_plies >= len(tokens):
                break

            mv = tokens[prefix_plies]
            board, row_idx = _apply_source_move(board, mv, strict_rows=True)

            if _has_four_from(board, row_idx, mv.col, mv.player):
                break

    return rows


def main() -> None:
    rng = random.Random(SEED)

    print("Parsing and validating curated Tromp/Allen lines...")
    sequences = _validated_sequences(strict_rows=True)
    print(f"Valid source lines: {len(sequences):,}/{len(CURATED_LINES):,}")

    all_rows: List[Dict[str, Any]] = []

    if INCLUDE_EXPERT_ROWS:
        expert_rows = build_expert_rows(sequences, rng=rng)
        print(f"Expert rows: {len(expert_rows):,}")
        all_rows.extend(expert_rows)

    if INCLUDE_LA_PREFIX_ROWS:
        for depth in LOOKAHEAD_DEPTHS:
            la_rows = build_la_prefix_rows(
                sequences,
                rng=rng,
                lookahead_depth=int(depth),
            )
            print(f"LA{int(depth)} prefix rows: {len(la_rows):,}")
            all_rows.extend(la_rows)
        


    df = _records_to_dataframe(all_rows)
    _write_output(df, OUTPUT_PATH, sheet_name=SHEET_NAME)

    print(f"Wrote {len(df):,} rows -> {OUTPUT_PATH}")

    if PRINT_FIRST_N_BOARDS > 0 and len(df) > 0:
        print("\nSanity preview:")
        for i in range(min(int(PRINT_FIRST_N_BOARDS), len(df))):
            row = df.iloc[i]
            print(
                f"\nrow={i} label={row['label']} game={row['game']} "
                f"ply={row['ply']} player={row['player']} action={row['action']}"
            )
            b = np.array([[int(row[f"{r}-{c}"]) for c in range(COLS)] for r in range(ROWS)], dtype=np.int8)
            _print_board(b)
            probs = {f"p{a}": float(row[f"p{a}"]) for a in range(COLS) if f"p{a}" in df.columns and float(row[f"p{a}"]) != 0.0}
            if probs:
                print("policy_probs =", probs)


if __name__ == "__main__":
    main()
